Added luanda to configuration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27,15 +27,28 @@ git submodule init > /dev/null
 git submodule update > /dev/null
 cd tbo
 ./configure
+cd ..
 
-echo -e "${LIGHTBLUE}building tbo library begins...${NC}"
+echo -e "${LIGHTBLUE}building tbo library...${NC}"
 echo -e "${LIGHTBLUE}Please wait. This may take a few seconds${NC}"
-cd build
+cd tbo/build
 if make -j static_library > /dev/null ;
 then
 	echo -e "${LIGHTGREEN}Building tbo library complete${NC}"
 else
 	echo -e "${LIGHTRED}Building tbo library error! Pls leave a message about the problem in https://github.com/vrodedanya/tbo${NC}"
+	exit 1
+fi
+cd ../..
+
+echo -e "${LIGHTBLUE}building luanda library...${NC}"
+echo -e "${LIGHTBLUE}Please wait. This may take a few seconds${NC}"
+cd luanda/build
+if make -j static_library > /dev/null ;
+then
+	echo -e "${LIGHTGREEN}Building luanda library complete${NC}"
+else
+	echo -e "${LIGHTRED}Building luanda library error! Pls leave a message about the problem in https://github.com/vrodedanya/luanda${NC}"
 	exit 1
 fi
 
